apiVersion: apps/v1
kind: Deployment
metadata:
  name: ee-medicine-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /ee-openapi
            - name: BASE_URL
              value: /ee-openapi-ui