apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ee-project-install  # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: ee-wac-hospital-project
spec:
  wait: true
  interval: 120s
  path: clusters/wac-aks/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: ee-project-gitops-repo