apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: ee-wac-hospital-project
      app.kubernetes.io/name: ee-medicine-inventory

namespace: ee-wac-hospital-project

resources:
  - cd.kustomization.yaml
  - install.kustomization.yaml
  - git-repository.yaml