apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: ee-wac-hospital-project

namespace: ee-wac-hospital-project

resources:
  - repository-pat.yaml