apiVersion: apps/v1
kind: Deployment
metadata:
  name: ee-medicine-inventory-deployment      # meno deployment-u od ktorého sa odvádza meno podu
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: ee-medicine-inventory-label    # tento riadok je len označenie štítku
                                          # key-value pair pod=medicine inventory
                                          # určený pre výber podov s rovnakým štítkom
  template: # šablóna pre vytvorenie replík podov
    metadata:
      labels:
        pod: ee-medicine-inventory-label    # štítky podu
    spec:
      containers:
        - name: medicine-inventory-container # meno kontaineru - v pod-e ich môže byť viac
          image: undy45/medicine-inventory
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080       # port na ktorom počúva kontajner, pomenovaný ako `http`

          resources:  # určenie kvót pre využívané fyzické prostriedky
                      # je dôležité pre riadenie záťaže v rámci kubernetes
                      # klastra
            requests:
              memory: "32M"
              cpu: "0.1"
            limits:
              memory: "320M"
              cpu: "0.3"