apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ee-medicine-inventory-content
spec:
  microFrontend: ee-medicine-inventory
  # aplication context element
  element: ee-medicine-app
  attributes:
    - name: api-base
      value: http://localhost:30081/api
    - name: ambulance-id
      value: bobulova
    - name: base-path
      value: /ee-medicine-app/
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?ee-medicine-inventory(/.*)?$"